In [2]:
import pandas as pd
from transformers import pipeline
from tqdm import tqdm

tqdm.pandas()

In [4]:
news_data = pd.read_csv('AAPL_NEWS_2024_2025.csv', index_col=0)
news_data

,symbol,publishedDate,title,image,site,text,url
0,AAPL,2025-02-12 13:23:14,Apple: Still Too Expensive For My Liking,https://images.financialmodelingprep.com/news/...,seekingalpha.com,Apple: Still Too Expensive For My Liking,https://seekingalpha.com/article/4757468-apple...
1,AAPL,2025-02-12 12:54:52,"Apple Teams Up With Alibaba for AI, Analyst Sa...",https://images.financialmodelingprep.com/news/...,benzinga.com,BofA Securities analyst Wamsi Mohan reiterated...,https://www.benzinga.com/analyst-ratings/price...
2,AAPL,2025-02-12 12:16:11,Apple Down 7% Year to Date on iPhone Weakness:...,https://images.financialmodelingprep.com/news/...,zacks.com,Although AAPL's AI push and growing Services b...,https://www.zacks.com/stock/news/2414741/apple...
3,AAPL,2025-02-12 09:05:00,Apple Device Security and Compliance Innovatio...,https://images.financialmodelingprep.com/news/...,businesswire.com,MIAMI--(BUSINESS WIRE)-- #Addigy--Addigy deliv...,https://www.businesswire.com/news/home/2025021...
4,AAPL,2025-02-12 09:01:23,Apple launches first major health study in 5 y...,https://images.financialmodelingprep.com/news/...,cnbc.com,"Apple launched the Apple Health Study, which w...",https://www.cnbc.com/2025/02/12/apple-launches...
...,...,...,...,...,...,...,...
15,AAPL,2024-09-09 10:44:56,Arm Stock Bounces Amid Apple Rumors,https://images.financialmodelingprep.com/news/...,schaeffersresearch.com,Shares of chipmaker Arm Holdings (NASDAQ:ARM)...,https://www.schaeffersresearch.com/content/new...
16,AAPL,2024-09-09 10:30:49,Apple Gears Up for Glowtime Event: ETFs in Focus,https://images.financialmodelingprep.com/news/...,zacks.com,Apple is set to unveil the iPhone 16 series sm...,https://www.zacks.com/stock/news/2333316/apple...
17,AAPL,2024-09-09 10:27:20,Apple's AI iPhone Debut: What To Expect For Ap...,https://images.financialmodelingprep.com/news/...,forbes.com,Apple will hold its annual September product l...,https://www.forbes.com/sites/dereksaul/2024/09...
18,AAPL,2024-09-09 10:05:34,Apple Inc. (AAPL) is Attracting Investor Atten...,https://images.financialmodelingprep.com/news/...,zacks.com,"Recently, Zacks.com users have been paying clo...",https://www.zacks.com/stock/news/2333264/apple...
19,AAPL,2024-09-09 09:13:35,Apple to launch new tech at its biggest event ...,https://images.financialmodelingprep.com/news/...,news.sky.com,Apple is launching its latest iPhone in what i...,https://news.sky.com/story/apple-to-launch-new...

In [5]:
classifier = pipeline('zero-shot-classification', model='facebook/bart-large-mnli')

Device set to use cpu

In [6]:
news_data.iloc[1, ]['title']

'Apple Teams Up With Alibaba for AI, Analyst Says Edge Device Integration Could Boost Growth'

In [7]:
candidate_labels = ['bullish', 'bearish']
classifier(news_data.iloc[1, ]['title'], candidate_labels)

{'sequence': 'Apple Teams Up With Alibaba for AI, Analyst Says Edge Device Integration Could Boost Growth',
 'labels': ['bullish', 'bearish'],
 'scores': [0.9959931969642639, 0.0040068007074296474]}

In [10]:
news_data.iloc[91, ]['title']

'Apple shares fall on concern Trump tariffs on China will hit profit'

In [12]:
candidate_labels = ['non-geopolitical', 'geopolitical']
classifier(news_data.iloc[91, ]['title'], candidate_labels)

{'sequence': 'Apple shares fall on concern Trump tariffs on China will hit profit',
 'labels': ['geopolitical', 'non-geopolitical'],
 'scores': [0.935115396976471, 0.06488458812236786]}

In [13]:
candidate_labels = ['prediction', 'reporting', 'other']
classifier(news_data.iloc[91, ]['title'], candidate_labels)

{'sequence': 'Apple shares fall on concern Trump tariffs on China will hit profit',
 'labels': ['reporting', 'prediction', 'other'],
 'scores': [0.637950599193573, 0.20151224732398987, 0.16053716838359833]}

In [14]:
sentiment_labels = ['positive', 'negative', 'neutral']
market_labels = ['bullish', 'bearish', 'neutral']
economic_labels = ['geopolitical', 'non-geopolitical']
outlook_labels = ['prediction', 'already happened', 'other']

In [15]:
classifier(news_data.iloc[1, ]['title'], sentiment_labels)

{'sequence': 'Apple Teams Up With Alibaba for AI, Analyst Says Edge Device Integration Could Boost Growth',
 'labels': ['positive', 'neutral', 'negative'],
 'scores': [0.9583668112754822, 0.03259569779038429, 0.009037517942488194]}

In [16]:
classifier(news_data.iloc[1, ]['title'], market_labels)

{'sequence': 'Apple Teams Up With Alibaba for AI, Analyst Says Edge Device Integration Could Boost Growth',
 'labels': ['bullish', 'neutral', 'bearish'],
 'scores': [0.9776900410652161, 0.01837681420147419, 0.0039331684820353985]}

In [17]:
classifier(news_data.iloc[1, ]['title'], economic_labels)

{'sequence': 'Apple Teams Up With Alibaba for AI, Analyst Says Edge Device Integration Could Boost Growth',
 'labels': ['non-geopolitical', 'geopolitical'],
 'scores': [0.9227890968322754, 0.0772109255194664]}

In [19]:
classifier(news_data.iloc[2, ]['title'], outlook_labels)

{'sequence': 'Apple Down 7% Year to Date on iPhone Weakness: Buy or Hold the Stock?',
 'labels': ['already happened', 'prediction', 'other'],
 'scores': [0.4420779347419739, 0.39033910632133484, 0.16758295893669128]}

In [20]:
news_data_sample = news_data.head(20)
news_data_sample = news_data_sample[['publishedDate', 'title']]
news_data_sample

          publishedDate                                              title
0   2025-02-12 13:23:14           Apple: Still Too Expensive For My Liking
1   2025-02-12 12:54:52  Apple Teams Up With Alibaba for AI, Analyst Sa...
2   2025-02-12 12:16:11  Apple Down 7% Year to Date on iPhone Weakness:...
3   2025-02-12 09:05:00  Apple Device Security and Compliance Innovatio...
4   2025-02-12 09:01:23  Apple launches first major health study in 5 y...
5   2025-02-12 09:00:00  Kandji Announces Vulnerability Management, Del...
6   2025-02-12 08:14:07  Apple Finds Its AI Wingman In Alibaba - Can It...
7   2025-02-12 07:22:00  Prediction: Warren Buffett and Berkshire Hatha...
8   2025-02-12 06:42:00  Alibaba's stock gets boost from reported Apple...
9   2025-02-12 06:12:00  Alibaba Stock Surges After AI Deal With Apple....
10  2025-02-12 05:30:00  Warren Buffett Sells Apple Stock and Buys an I...
11  2025-02-12 04:32:00       Best Stock to Buy Right Now: Amazon vs Apple
13  2025-02-12 02:47:45  Alibaba's Shares Surge On Report Of AI Partner...
14  2025-02-11 23:32:23  Despite an Alibaba-Apple Boost, Here's Why Sto...
15  2025-02-11 18:49:44  Apple expected to unveil new iPhone SE, plus p...
16  2025-02-11 16:46:11  Will Apple's AI Partnership With Alibaba Solve...
17  2025-02-11 16:29:55  Report: Apple working on AI partnership with A...
18  2025-02-11 11:26:56  Apple Reportedly Links With Alibaba for Chines...
19  2025-02-11 11:04:30  Apple reportedly partners with Alibaba after r...
0   2025-02-11 09:30:37         Apple Stock A Smarter AI Play Than Nvidia?

In [21]:
news_data_sample['sentiment'] = news_data_sample['title'].progress_apply(lambda x: classifier(x, sentiment_labels)['labels'][0])

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:36<00:00,  1.81s/it]

In [22]:
news_data_sample

,publishedDate,title,sentiment
0,2025-02-12 13:23:14,Apple: Still Too Expensive For My Liking,negative
1,2025-02-12 12:54:52,"Apple Teams Up With Alibaba for AI, Analyst Sa...",positive
2,2025-02-12 12:16:11,Apple Down 7% Year to Date on iPhone Weakness:...,negative
3,2025-02-12 09:05:00,Apple Device Security and Compliance Innovatio...,positive
4,2025-02-12 09:01:23,Apple launches first major health study in 5 y...,positive
5,2025-02-12 09:00:00,"Kandji Announces Vulnerability Management, Del...",positive
6,2025-02-12 08:14:07,Apple Finds Its AI Wingman In Alibaba - Can It...,positive
7,2025-02-12 07:22:00,Prediction: Warren Buffett and Berkshire Hatha...,negative
8,2025-02-12 06:42:00,Alibaba's stock gets boost from reported Apple...,positive
9,2025-02-12 06:12:00,Alibaba Stock Surges After AI Deal With Apple....,positive
10,2025-02-12 05:30:00,Warren Buffett Sells Apple Stock and Buys an I...,positive
11,2025-02-12 04:32:00,Best Stock to Buy Right Now: Amazon vs Apple,positive
13,2025-02-12 02:47:45,Alibaba's Shares Surge On Report Of AI Partner...,positive
14,2025-02-11 23:32:23,"Despite an Alibaba-Apple Boost, Here's Why Sto...",negative
15,2025-02-11 18:49:44,"Apple expected to unveil new iPhone SE, plus p...",positive
16,2025-02-11 16:46:11,Will Apple's AI Partnership With Alibaba Solve...,positive
17,2025-02-11 16:29:55,Report: Apple working on AI partnership with A...,positive
18,2025-02-11 11:26:56,Apple Reportedly Links With Alibaba for Chines...,positive
19,2025-02-11 11:04:30,Apple reportedly partners with Alibaba after r...,negative
0,2025-02-11 09:30:37,Apple Stock A Smarter AI Play Than Nvidia?,positive

In [23]:
news_data_sample['market_outlook'] = news_data_sample['title'].progress_apply(lambda x: classifier(x, market_labels)['labels'][0])
news_data_sample['economic'] = news_data_sample['title'].progress_apply(lambda x: classifier(x, economic_labels)['labels'][0])
news_data_sample['article_nature'] = news_data_sample['title'].progress_apply(lambda x: classifier(x, outlook_labels)['labels'][0])

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:35<00:00,  1.79s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.24s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:37<00:00,  1.86s/it]

In [24]:
news_data_sample

,publishedDate,title,sentiment,market_outlook,economic,article_nature
0,2025-02-12 13:23:14,Apple: Still Too Expensive For My Liking,negative,bearish,non-geopolitical,prediction
1,2025-02-12 12:54:52,"Apple Teams Up With Alibaba for AI, Analyst Sa...",positive,bullish,non-geopolitical,other
2,2025-02-12 12:16:11,Apple Down 7% Year to Date on iPhone Weakness:...,negative,bearish,non-geopolitical,already happened
3,2025-02-12 09:05:00,Apple Device Security and Compliance Innovatio...,positive,bullish,non-geopolitical,already happened
4,2025-02-12 09:01:23,Apple launches first major health study in 5 y...,positive,bullish,non-geopolitical,other
5,2025-02-12 09:00:00,"Kandji Announces Vulnerability Management, Del...",positive,bullish,non-geopolitical,already happened
6,2025-02-12 08:14:07,Apple Finds Its AI Wingman In Alibaba - Can It...,positive,bullish,non-geopolitical,prediction
7,2025-02-12 07:22:00,Prediction: Warren Buffett and Berkshire Hatha...,negative,bearish,non-geopolitical,prediction
8,2025-02-12 06:42:00,Alibaba's stock gets boost from reported Apple...,positive,bullish,non-geopolitical,prediction
9,2025-02-12 06:12:00,Alibaba Stock Surges After AI Deal With Apple....,positive,bullish,non-geopolitical,prediction
10,2025-02-12 05:30:00,Warren Buffett Sells Apple Stock and Buys an I...,positive,bullish,non-geopolitical,prediction
11,2025-02-12 04:32:00,Best Stock to Buy Right Now: Amazon vs Apple,positive,bullish,non-geopolitical,prediction
13,2025-02-12 02:47:45,Alibaba's Shares Surge On Report Of AI Partner...,positive,bullish,non-geopolitical,prediction
14,2025-02-11 23:32:23,"Despite an Alibaba-Apple Boost, Here's Why Sto...",negative,bearish,non-geopolitical,prediction
15,2025-02-11 18:49:44,"Apple expected to unveil new iPhone SE, plus p...",positive,bullish,non-geopolitical,prediction
16,2025-02-11 16:46:11,Will Apple's AI Partnership With Alibaba Solve...,positive,bullish,geopolitical,prediction
17,2025-02-11 16:29:55,Report: Apple working on AI partnership with A...,positive,bullish,non-geopolitical,other
18,2025-02-11 11:26:56,Apple Reportedly Links With Alibaba for Chines...,positive,bullish,non-geopolitical,other
19,2025-02-11 11:04:30,Apple reportedly partners with Alibaba after r...,negative,bearish,non-geopolitical,other
0,2025-02-11 09:30:37,Apple Stock A Smarter AI Play Than Nvidia?,positive,bullish,non-geopolitical,other